/*
SELECT D.NAME, FIRSTNAME, LASTNAME
FROM EMPLOYEE JOIN  DEPARTMENT D
ON D.ID=ID_DEPARTMENT
WHERE  CITY LIKE 'LVIV' AND POSITION LIKE 'MANAGER'
*/
SELECT D.NAME, EMPL.FIRSTNAME, EMPL.LASTNAME
FROM (SELECT FIRSTNAME, LASTNAME, ID_DEPARTMENT
             FROM EMPLOYEE
             WHERE POSITION LIKE 'MANAGER') EMPL JOIN
       DEPARTMENT D ON D.ID=EMPL.ID_DEPARTMENT
WHERE  CITY LIKE 'LVIV'