SELECT NAME, POSITION, AVG(RATE)
FROM DEPARTMENT D JOIN EMPLOYEE E
         ON  D.ID =ID_DEPARTMENT
GROUP BY NAME, POSITION
HAVING AVG(RATE)>=(SELECT AVG(RATE) FROM EMPLOYEE WHERE POSITION = E.POSITION)
