/*
SELECT LASTNAME, RATE, ID_DEPARTMENT
FROM EMPLOYEE EMP
WHERE EXISTS (SELECT ID
	FROM EMPLOYEE
	WHERE ID_BOSS = EMP.ID)
ORDER BY ID_DEPARTMENT
*/
SELECT NAME, ID
FROM DEPARTMENT D
WHERE NOT EXISTS (SELECT *
	FROM EMPLOYEE
	WHERE ID_DEPARTMENT = D.ID)
