/*
SELECT NAME, COUNT(EMPLOYEE.ID) COUNT_EMPLOYEE
FROM DEPARTMENT LEFT JOIN EMPLOYEE
ON DEPARTMENT.ID = ID_DEPARTMENT
GROUP BY NAME
*/

SELECT NAME,
(SELECT COUNT(*)
 FROM EMPLOYEE
 WHERE ID_DEPARTMENT = DEPARTMENT.ID) COUNT_EMPLOYEE
FROM DEPARTMENT
