SELECT FIRSTNAME, LASTNAME, PRODUCT_NAME
FROM CUSTOMERS c
left join ORDERS o
on c.id=o.ID_CUSTOMER
union
SELECT FIRSTNAME, LASTNAME, PRODUCT_NAME
FROM CUSTOMERS c
right join ORDERS o
on c.id=o.ID_CUSTOMER
